spring.application.name=esientradas

#BASE DE DATOS (ACCESO SI USAMOS SPRING)
#spring.datasource.url = jdbc:mysql://172.20.48.23:3306/gramola?serverTimezone=UTC&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&maxAllowedPacket=134217728
spring.datasource.url = jdbc:mysql://localhost:3306/esientradas?serverTimezone=UTC&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&maxAllowedPacket=134217728
spring.datasource.username = root
spring.datasource.password = Msi2560

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

server.error.include-message=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# URL base del servicio de usuarios externos (modificar según entorno)
esiusuarios.url=http://localhost:8081

# ============================================================
# EMAIL - Brevo (API para el envío de PDFs)
# ============================================================
brevo.api.url=https://api.brevo.com/v3/smtp/email
brevo.api.key=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

app.mail.from=edugallego23@gmail.com
app.mail.from.name=ESIentradas


# IP de tu PC para que los enlaces del correo funcionen en el móvil
app.base-url=http://192.168.1.40:8080
